### ISSUE TITLE
Import should accept week number

### ISSUE THREAD

**Issue by khakulov** [it-roockies/timetable-backend#1]
store timetable data for given week

Data comes from frontend like `2021-W12` The name of field `week`

```python
from datetime import datetime
datetime.strptime("2021-W12-1", "%Y-W%W-%w")
```

**Comment by khakulov** [comment]
https://stackoverflow.com/questions/17087314/get-date-from-week-number

**Comment by DiyorbekAzimqulov** [comment]
It is done

**Comment by khakulov** [comment]
thanks
